### ISSUE TITLE
Problem with librealsense

### ISSUE THREAD

**Issue by alfred316** [intel/collision-avoidance-library#139]
Hello everyone, 

I am currently trying to work through these steps on Ubuntu 16.04.2 and I am running into an issue regarding librealsense. So when I got to that step to go to the link with the librealsense steps, I followed all the steps in there and got to the point where it said to "navigate to librealsense root directory". I could not find a root directory for librealsense anywhere and found a forum response on the intel forums that said to clone the librealsense library and work from there. So I did that, made the build folder in it, continued the steps and they all worked fine. 

I made it to the point where I had to make a build folder in the root of the collision avoidance project and go in there and run cmake .. which worked after I had to manually set locations for the REALSENSE_INCLUDE_DIR and REALSENSE_LIBRARY in cmake, which I have set to /usr/local/include/librealsense2 and /usr/local/include/librealsense2/rc.hpp respectively. However, when I go to do the next step, which is "sudo make install" it stops at 73% and I get this error:
fatal error: librealsense/rs.hpp: No such file or directory

So, this is where I'm stuck. Any idea where I messed up or what I could do to get around this error? Did I put something in the wrong place? Did I do something out of order? 

I would appreciate any advice or help and if you want more information about specific things I did during this process, just let me know. 

Thank you for your time
Sincerely
Alfred Shaker

**Comment by rchiossi** [comment]
Hi,
Where exactly is that "navigate to librealsense root directory" step? I'm not sure I know what steps you are talking about.

**Comment by anselmolsm** [comment]
"navigate to librealsense root directory" means "cd path-to-dir-where-librealsense-has-been-cloned".

I see in your comment references to librealsense2. This library has not been ported to use librealsense2 yet.

**Comment by alfred316** [comment]
I ended up using snap to install it and get it working, thank you for the responses.
